apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-v2
  labels:
    app: tetris-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris-v2
  template:
    metadata:
      labels:
        app: tetris-v2
    spec:
      containers:
        - name: tetris-v2
          image: abmaxx/tetris-v2:379713f08828e45aa951a172ecf4bae1532dacf8
          ports:
            - containererPort: 80
