apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-v2
  labels:
    app: tetris-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris-v2
  template:
    metadata:
      labels:
        app: tetris-v2
    spec:
      containers:
        - name: tetris-v2
          image: abmaxx/tetris-v2:75bbb7f429c37df306c309fbfe99b827763c5dc6
          ports:
            - containerPort: 80
